// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmAd3OYkJfJ0QKp6lhPTBgDrEURoeUBDw',
    appId: '1:530280250078:web:6ac709880c6494020d204f',
    messagingSenderId: '530280250078',
    projectId: 'tomatoes-f33c6',
    authDomain: 'tomatoes-f33c6.firebaseapp.com',
    databaseURL: 'https://tomatoes-f33c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tomatoes-f33c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAng3tBWmp9rfG_5e8gGRgsDhWqKQT1Yag',
    appId: '1:530280250078:android:a417cc0af56307fc0d204f',
    messagingSenderId: '530280250078',
    projectId: 'tomatoes-f33c6',
    databaseURL: 'https://tomatoes-f33c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tomatoes-f33c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwoATUeKo8WG79vlpfGoVMhje6TEeW7EQ',
    appId: '1:530280250078:ios:f34c818e7a2cf4c70d204f',
    messagingSenderId: '530280250078',
    projectId: 'tomatoes-f33c6',
    databaseURL: 'https://tomatoes-f33c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tomatoes-f33c6.appspot.com',
    iosBundleId: 'com.example.tinhtoandidongProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwoATUeKo8WG79vlpfGoVMhje6TEeW7EQ',
    appId: '1:530280250078:ios:f34c818e7a2cf4c70d204f',
    messagingSenderId: '530280250078',
    projectId: 'tomatoes-f33c6',
    databaseURL: 'https://tomatoes-f33c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tomatoes-f33c6.appspot.com',
    iosBundleId: 'com.example.tinhtoandidongProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmAd3OYkJfJ0QKp6lhPTBgDrEURoeUBDw',
    appId: '1:530280250078:web:8ee74a2ef701c7fe0d204f',
    messagingSenderId: '530280250078',
    projectId: 'tomatoes-f33c6',
    authDomain: 'tomatoes-f33c6.firebaseapp.com',
    databaseURL: 'https://tomatoes-f33c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tomatoes-f33c6.appspot.com',
  );

}